env: "local"

db:
  bdpath: "myDB/db"
  
logging:
  app_log: "src/cmd/server-starter/app.log"  
  level: "debug"                            

server:
  adr: "localhost:8080"
  static_dir: "static"                      